package dev.dediren.contracts.render;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum SvgNodeDecorator {
    @JsonProperty("archimate_plateau")
    ARCHIMATE_PLATEAU,
    @JsonProperty("archimate_work_package")
    ARCHIMATE_WORK_PACKAGE,
    @JsonProperty("archimate_deliverable")
    ARCHIMATE_DELIVERABLE,
    @JsonProperty("archimate_implementation_event")
    ARCHIMATE_IMPLEMENTATION_EVENT,
    @JsonProperty("archimate_gap")
    ARCHIMATE_GAP,
    @JsonProperty("archimate_grouping")
    ARCHIMATE_GROUPING,
    @JsonProperty("archimate_and_junction")
    ARCHIMATE_AND_JUNCTION,
    @JsonProperty("archimate_or_junction")
    ARCHIMATE_OR_JUNCTION,
    @JsonProperty("archimate_location")
    ARCHIMATE_LOCATION,
    @JsonProperty("archimate_stakeholder")
    ARCHIMATE_STAKEHOLDER,
    @JsonProperty("archimate_driver")
    ARCHIMATE_DRIVER,
    @JsonProperty("archimate_assessment")
    ARCHIMATE_ASSESSMENT,
    @JsonProperty("archimate_goal")
    ARCHIMATE_GOAL,
    @JsonProperty("archimate_outcome")
    ARCHIMATE_OUTCOME,
    @JsonProperty("archimate_value")
    ARCHIMATE_VALUE,
    @JsonProperty("archimate_meaning")
    ARCHIMATE_MEANING,
    @JsonProperty("archimate_constraint")
    ARCHIMATE_CONSTRAINT,
    @JsonProperty("archimate_requirement")
    ARCHIMATE_REQUIREMENT,
    @JsonProperty("archimate_principle")
    ARCHIMATE_PRINCIPLE,
    @JsonProperty("archimate_course_of_action")
    ARCHIMATE_COURSE_OF_ACTION,
    @JsonProperty("archimate_resource")
    ARCHIMATE_RESOURCE,
    @JsonProperty("archimate_value_stream")
    ARCHIMATE_VALUE_STREAM,
    @JsonProperty("archimate_capability")
    ARCHIMATE_CAPABILITY,
    @JsonProperty("archimate_business_interface")
    ARCHIMATE_BUSINESS_INTERFACE,
    @JsonProperty("archimate_business_collaboration")
    ARCHIMATE_BUSINESS_COLLABORATION,
    @JsonProperty("archimate_business_actor")
    ARCHIMATE_BUSINESS_ACTOR,
    @JsonProperty("archimate_business_role")
    ARCHIMATE_BUSINESS_ROLE,
    @JsonProperty("archimate_business_service")
    ARCHIMATE_BUSINESS_SERVICE,
    @JsonProperty("archimate_business_interaction")
    ARCHIMATE_BUSINESS_INTERACTION,
    @JsonProperty("archimate_business_function")
    ARCHIMATE_BUSINESS_FUNCTION,
    @JsonProperty("archimate_business_process")
    ARCHIMATE_BUSINESS_PROCESS,
    @JsonProperty("archimate_business_event")
    ARCHIMATE_BUSINESS_EVENT,
    @JsonProperty("archimate_product")
    ARCHIMATE_PRODUCT,
    @JsonProperty("archimate_business_object")
    ARCHIMATE_BUSINESS_OBJECT,
    @JsonProperty("archimate_contract")
    ARCHIMATE_CONTRACT,
    @JsonProperty("archimate_representation")
    ARCHIMATE_REPRESENTATION,
    @JsonProperty("archimate_application_interface")
    ARCHIMATE_APPLICATION_INTERFACE,
    @JsonProperty("archimate_application_collaboration")
    ARCHIMATE_APPLICATION_COLLABORATION,
    @JsonProperty("archimate_application_component")
    ARCHIMATE_APPLICATION_COMPONENT,
    @JsonProperty("archimate_application_service")
    ARCHIMATE_APPLICATION_SERVICE,
    @JsonProperty("archimate_application_interaction")
    ARCHIMATE_APPLICATION_INTERACTION,
    @JsonProperty("archimate_application_function")
    ARCHIMATE_APPLICATION_FUNCTION,
    @JsonProperty("archimate_application_process")
    ARCHIMATE_APPLICATION_PROCESS,
    @JsonProperty("archimate_application_event")
    ARCHIMATE_APPLICATION_EVENT,
    @JsonProperty("archimate_data_object")
    ARCHIMATE_DATA_OBJECT,
    @JsonProperty("archimate_technology_interface")
    ARCHIMATE_TECHNOLOGY_INTERFACE,
    @JsonProperty("archimate_technology_collaboration")
    ARCHIMATE_TECHNOLOGY_COLLABORATION,
    @JsonProperty("archimate_technology_node")
    ARCHIMATE_TECHNOLOGY_NODE,
    @JsonProperty("archimate_system_software")
    ARCHIMATE_SYSTEM_SOFTWARE,
    @JsonProperty("archimate_device")
    ARCHIMATE_DEVICE,
    @JsonProperty("archimate_facility")
    ARCHIMATE_FACILITY,
    @JsonProperty("archimate_equipment")
    ARCHIMATE_EQUIPMENT,
    @JsonProperty("archimate_path")
    ARCHIMATE_PATH,
    @JsonProperty("archimate_technology_service")
    ARCHIMATE_TECHNOLOGY_SERVICE,
    @JsonProperty("archimate_technology_interaction")
    ARCHIMATE_TECHNOLOGY_INTERACTION,
    @JsonProperty("archimate_technology_function")
    ARCHIMATE_TECHNOLOGY_FUNCTION,
    @JsonProperty("archimate_technology_process")
    ARCHIMATE_TECHNOLOGY_PROCESS,
    @JsonProperty("archimate_technology_event")
    ARCHIMATE_TECHNOLOGY_EVENT,
    @JsonProperty("archimate_artifact")
    ARCHIMATE_ARTIFACT,
    @JsonProperty("archimate_material")
    ARCHIMATE_MATERIAL,
    @JsonProperty("archimate_communication_network")
    ARCHIMATE_COMMUNICATION_NETWORK,
    @JsonProperty("archimate_distribution_network")
    ARCHIMATE_DISTRIBUTION_NETWORK,
    @JsonProperty("uml_package")
    UML_PACKAGE,
    @JsonProperty("uml_class")
    UML_CLASS,
    @JsonProperty("uml_interface")
    UML_INTERFACE,
    @JsonProperty("uml_data_type")
    UML_DATA_TYPE,
    @JsonProperty("uml_enumeration")
    UML_ENUMERATION,
    @JsonProperty("uml_activity")
    UML_ACTIVITY,
    @JsonProperty("uml_action")
    UML_ACTION,
    @JsonProperty("uml_initial_node")
    UML_INITIAL_NODE,
    @JsonProperty("uml_activity_final_node")
    UML_ACTIVITY_FINAL_NODE,
    @JsonProperty("uml_decision_node")
    UML_DECISION_NODE,
    @JsonProperty("uml_merge_node")
    UML_MERGE_NODE,
    @JsonProperty("uml_fork_node")
    UML_FORK_NODE,
    @JsonProperty("uml_join_node")
    UML_JOIN_NODE,
    @JsonProperty("uml_object_node")
    UML_OBJECT_NODE,
    @JsonProperty("uml_interaction")
    UML_INTERACTION,
    @JsonProperty("uml_lifeline")
    UML_LIFELINE,
    @JsonProperty("uml_execution_specification")
    UML_EXECUTION_SPECIFICATION,
    @JsonProperty("uml_gate")
    UML_GATE,
    @JsonProperty("uml_destruction_occurrence")
    UML_DESTRUCTION_OCCURRENCE,
    @JsonProperty("uml_state_machine")
    UML_STATE_MACHINE,
    @JsonProperty("uml_region")
    UML_REGION,
    @JsonProperty("uml_state")
    UML_STATE,
    @JsonProperty("uml_final_state")
    UML_FINAL_STATE,
    @JsonProperty("uml_pseudostate")
    UML_PSEUDOSTATE
}
